#1 - This name will be used in the next step when creating the Automation Hub instance
#2 - If the secret was changed when creating the Keycloak client for Automation Hub be sure to change this value to match 
#3 - The value is the public_key found in the previous step 
# .  - Retreive the RH-SSO Public Key for the AAP realm
#     - Browse to https://<sso_host>/auth/realms/ansible-automation-platform
# .     Copy/Save the public_key value for use below
apiVersion: v1
kind: Secret
metadata:
  name: automation-hub-sso                       #(1)
  namespace: ansible-automation-platform
type: Opaque
stringData:
  keycloak_host: "keycloak-rh-sso.apps-crc.testing"
  keycloak_port: "443"
  keycloak_protocol: "https"
  keycloak_realm: "ansible-automation-platform"
  keycloak_admin_role: "hubadmin"
  social_auth_keycloak_key: "automation-hub"
  social_auth_keycloak_secret: "client-secret"   #(2)
  social_auth_keycloak_public_key: >-            #(3)
    CHANGE-THIS-PLEASE-MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi9+C4v9fHF3XD14JRxXrGXF8tHNv7XlNyDMbsiPe8ROcjGCHSu6pEd2r48fgD58FrUx8cKDo9ff38h26Ytsv0y+DB0QmYOhjEqUQezLf9V5pft4xhnH24XeS8DmSoIdHfBOoY0/cNwBaUXOpmFk93E8NaLfqCgWUR7HRWPAJvWCrqFykjgSD/Z8MK2hxLAkvTKFx0oI30mbtBuuzahB4lqjenz/hQNmTNQSa0WBHrq9vm1uYuaAUR6B8ytbQ3NfFzaKiUu5AGZl8b9WUqJBYXXkfVQn51nLF7ccCwVsOGNwzyf5w1Su07INHFJAwJY/9ma+9asJq5B1j7glncLY6hwIDAQAB
