#1-Set this to the name to use for the instance
#2-Set this to the name of the secret previously created 
# . `5-rh-sso-connection-secret.yml`
#3-To use Openshift host storage, this only autocreated a PVC when 
# . the size was != 100Gi 

apiVersion: automationhub.ansible.com/v1beta1
kind: AutomationHub
metadata:
  name: private-ah                              #(1)
  namespace: ansible-automation-platform
spec:
  sso_secret: automation-hub-sso                #(2)
  pulp_settings:
    verify_ssl: false
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  loadbalancer_port: 80
  file_storage_size: 100Gi                      #(3) ~30Gi as 100Gi didn't autocreate a Volume and PVC
  image_pull_policy: IfNotPresent
  web:
    replicas: 1
  file_storage_access_mode: ReadWriteMany
  content:
    log_level: INFO
    replicas: 2
  postgres_storage_requirements:
    limits:
      storage: 50Gi
    requests:
      storage: 8Gi
  api:
    log_level: INFO
    replicas: 1
  postgres_resource_requirements:
    limits:
      cpu: 1000m
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 2Gi
  loadbalancer_protocol: http
  resource_manager:
    replicas: 1
  worker:
    replicas: 2
